### ISSUE TITLE
Kx12to13 After Conversion Page Markup Issues

### ISSUE THREAD

**Issue by GitRay07** [KenticoDevTrev/KX12To13Converter#14]
Hi Fayas,

I used the Kx12to13 converter and everything seems to have gone very smoothly. Now I'm putting each page together to display all document content accordingly.

However, I keep getting the following message: 

Message: Areas with the following identifiers are missing from page markup: editabletext3, editabletext6, editabletext4, editabletext5, IntroText, editabletext1. Saving the page will result in lost data.

No matter How I set it up, it still does not work!

I have added all related components, sections, and what not including the one at the view level.

<editable-area area-identifier="EditableText" area-options-allowed-widgets="@AreaRestrictionHelper.GetHomePageRestrictions()" />

or 

@await Html.Kentico().EditableAreaAsync("EditableText1")
@await Html.Kentico().EditableAreaAsync("EditableText3")
@await Html.Kentico().EditableAreaAsync("EditableText4")
@await Html.Kentico().EditableAreaAsync("EditableText5")
@await Html.Kentico().EditableAreaAsync("EditableText6")

Please advice..

Best regards,

Ray

**Comment by KenticoDevTrev** [comment]
Email me at tfayas@gmail.com and I can do a call with ya and take a look, the database will help me figure this one out for ya

**Comment by roryaherne** [comment]
Hi,

just one thing to note is that the converter takes the identifiers from what you see under the Web Parts tab in the Page Templates module in K12. These seem to keep previously deleted sections that are no longer visible in the design/layout tabs.

Best,
Rory

**Comment by KenticoDevTrev** [comment]
Yup, because they do technically still exist, you can in the converter I think set it to ignore those items
