### ISSUE TITLE
Conversions Interface UI grid error

### ISSUE THREAD

**Issue by jknaak** [KenticoDevTrev/KX12To13Converter#4]
When filtering in the conversions interface, I tried to search Notes IsNotEmpty.  Everything else was default value and received and error.  I have attached the log for reference.
[eventdetails.txt](https://github.com/KenticoDevTrev/KX12To13Converter/files/9634768/eventdetails.txt)

**Comment by KenticoDevTrev** [comment]
Fixed so won't error, Notes "is not empty" and "is empty" really don't do anything as no notes has a value of [] (empty array).

I added a "Has Notes" filter underneath so you can filter if they have notes or not (no notes in this case will be [])
